name: nirvanafit
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_icon_snackbar: ^1.1.4              # For showing animated snackbar with icons
  icons_launcher: ^3.0.0                     # For setting app launcher icon in ios and android
  font_awesome_flutter: ^10.5.0              # For using More icons
  google_fonts: 6.2.1                        # For using Google Fonts
  provider: ^6.1.2                           # For state management
  flutter_native_splash: ^2.4.4              # For setting splash screen

#  permission_handler: ^11.4.0               # For handling permissions
  shared_preferences: ^2.5.2                 # For storing key-value pairs
  url_launcher: ^6.3.1                       # For launching URLs
  curved_navigation_bar: ^1.0.6              # For using curved bottom navigation bar
  introduction_screen: ^3.1.14               # For showing onboarding screens
  flutter_carousel_widget: ^3.1.0            # For using carousel widget
  just_audio: ^0.9.46                        # For playing audio
#  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/animations/gifs/
    - assets/audio/
    - assets/fonts/
    - assets/icons/
    - assets/icons/my_app_icons/
    - assets/images/
    - assets/images/soothing_music/
    - assets/images/binaural_beats/
    - assets/images/exercises_challenges/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

icons_launcher:
  image_path: "assets/icons/my_app_icons/nirvana_mind_body.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_maskable: true
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  color: "#F5F5F5"
  image: assets/icons/splash_screen_icon.png
  branding: assets/icons/mysterious_coder_branding_icon.png
#  color_dark: "#000000"
#  image_dark: assets/icons/splash_screen.jpg
  android: true
  ios: true
  android_12:
    color: "#F5F5F5"
    image: assets/icons/splash_screen_icon.png
    branding: assets/icons/mysterious_coder_branding_icon.png
#    color_dark: "#000000"
#    image_dark: assets/icons/splash_screen.jpg
